spring.application.name=liquibase-demo

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/liquibase_demo_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.liquibase.change-log=classpath:/db/changelog/ChangeLogFile.xml
